import { defineConfig } from '@hey-api/openapi-ts';

export default defineConfig({
  input: '../../openapi.yaml',
  // postProcess: [] replaces the deprecated format:false / lint:false. The
  // generated tree is committed output, so nothing reformats it after us.
  output: { path: 'src/generated', postProcess: [] },
  plugins: [
    // The fetch client is emitted into src/generated by the generator itself.
    // There is no runtime dependency on @hey-api/client-fetch; that package was
    // folded into @hey-api/openapi-ts in v0.73.0 and is deprecated on npm.
    { name: '@hey-api/client-fetch', baseUrl: 'https://api.xdataapi.io' },
    '@hey-api/typescript',
    // 'flat' is the replacement for the deprecated asClass:false: standalone
    // functions, no classes, so the SDK stays tree-shakeable.
    { name: '@hey-api/sdk', operations: { strategy: 'flat' } },
  ],
});
